# -*- coding: utf-8 -*-
"""Neural network Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jF4A2PqtRxsw0WUshM7LlZx_rv0R0Z6x
"""

# ======================================
# 1. Import Libraries
# ======================================
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPRegressor
from sklearn.metrics import mean_squared_error

# ======================================
# 2. Load Dataset (GitHub)
# ======================================
url = "https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv"
df = pd.read_csv(url)

# Features & Target
X = df.drop("medv",axis=1)
y = df["medv"] # Numeric DV

# ======================================
# 3. Train-Test Split
# ======================================
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)


# ======================================
# 4. Feature Scaling
# ======================================
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# ======================================
# 5. Neural Network Model
# ======================================
model = MLPRegressor(
    hidden_layer_sizes=(50,50), # 2 hidden layers
    activation='relu',
    solver='adam',
    max_iter=1,       # train manually for epochs
    warm_start=True,  # retain weights across epochs
    random_state=42
)

# ================================
# 🔹 6. Train Model & Track Loss per Epoch
# ================================
epochs = 100
train_loss = []
test_loss = []

for i in range(epochs):
    model.fit(X_train, y_train)

    # Predictions
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)

    # Compute MSE
    train_loss.append(mean_squared_error(y_train, y_train_pred))
    test_loss.append(mean_squared_error(y_test, y_test_pred))

# ================================
# 🔹 7. Plot Train vs Test Loss (Epoch Graph)
# ================================
plt.plot(range(epochs), train_loss, label="Train Loss")
plt.plot(range(epochs), test_loss, label="Test Loss")
plt.xlabel("Epoch")
plt.ylabel("MSE Loss")
plt.title("Neural Network: Train vs Test Loss")
plt.legend()
plt.show()

# ================================
# 🔹 8. Final Model Performance
# ================================
print("Final Train Score (R2):", model.score(X_train, y_train))
print("Final Test Score (R2):", model.score(X_test, y_test))

# ================================
# 🔹 9. Hyperparameter Tuning (GridSearch)
# ================================
param_grid = {
    'hidden_layer_sizes': [(50,), (50,50), (100,)],
    'activation': ['relu', 'tanh'],
    'learning_rate_init': [0.001, 0.01]
}

# NOTE: Use fresh model without warm_start for tuning
grid_model = MLPRegressor(max_iter=500, random_state=42)

grid = GridSearchCV(grid_model, param_grid, cv=3, scoring='neg_mean_squared_error')
grid.fit(X_train, y_train)

# Best Parameters
print("Best Parameters:", grid.best_params_)

# Evaluate Best Model
best_model = grid.best_estimator_
y_pred_best = best_model.predict(X_test)

print("Best Model Test MSE:", mean_squared_error(y_test, y_pred_best))
print("Best Model Test R2:", best_model.score(X_test, y_test))

"""**Neural Network Classification**"""

# ================================
# 🔹 1. Import Libraries
# ================================
import numpy as np
import matplotlib.pyplot as plt

from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# ================================
# 🔹 2. Load Inbuilt Dataset
# ================================
data = load_breast_cancer()
X = data.data
y = data.target   # Binary target (0 = malignant, 1 = benign)

# ================================
# 🔹 3. Train-Test Split
# ================================
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# ================================
# 🔹 4. Feature Scaling
# ================================
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# ================================
# 🔹 5. Build Neural Network Classifier
# ================================
model = MLPClassifier(
    hidden_layer_sizes=(50, 50),
    activation='relu',
    solver='adam',
    max_iter=1,       # manual epoch control
    warm_start=True,  # retain weights across epochs
    random_state=42
)

# ================================
# 🔹 6. Train Model & Track Loss
# ================================
epochs = 100
loss_values = []

for i in range(epochs):
    model.fit(X_train, y_train)
    loss_values.append(model.loss_)

# ================================
# 🔹 7. Plot Loss vs Epoch
# ================================
plt.plot(range(epochs), loss_values)
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("NN Classifier Loss vs Epoch")
plt.show()

# ================================
# 🔹 8. Model Evaluation
# ================================
y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

